### ISSUE TITLE
route included in set, with ROA only, no route-object

### ISSUE THREAD

**Issue by m0yellow** [bgp/bgpq4#100]
Hello,
while investigating a route filter mismatch between level3 filtergen and bgpq4, I noticed bgpq3 was not including the route in question. 
At the time of writing, the route has valid RPKI, but no route object for any AS number.

The filter we are generating is an AS-SET, and the Route has the ROA on one AS number in the set.

I was unsure if and how to include the AS Number, so I opted for a link and picture to not draw too much attention to this particular route.
https://irrexplorer.nlnog.net/prefix/146.66.64.0/18
<img width="1194" alt="Screenshot 2023-11-17 at 12 13 53" src="https://github.com/bgp/bgpq4/assets/2116846/bd0f09d1-f85c-4f74-b9b4-42138118c96b">

expected behaviour would naively be to not include the route, as there isn't any route object anywhere. If you do not agree, I would kindly ask for your rationale why it should be included in the output.

**Comment by MrHamel** [comment]
The holder of the IP resources cryptographically said that those 3 ASNs are allowed to announce route up to a /24. That has more trust in my book than a random route(6) object in any IRR (including ALTNET, RADB).

**Comment by lukastribus** [comment]
bgpq4 by uses `rr.ntt.net`, bgpq3 uses by default `whois.radb.net`.

NTT's IRRD includes ROA as route-object. This is an expected and good thing.


```
~$ whois -h rr.ntt.net 146.66.64.0/18
route:          146.66.64.0/18
descr:          RPKI ROA for 146.66.64.0/18 / AS14618
remarks:        This AS14618 route object represents routing data retrieved
                from the RPKI. This route object is the result of an automated
                RPKI-to-IRR conversion process performed by IRRd.
max-length:     24
origin:         AS14618
source:         RPKI  # Trust Anchor: ripe

route:          146.66.64.0/18
descr:          RPKI ROA for 146.66.64.0/18 / AS16509
remarks:        This AS16509 route object represents routing data retrieved
                from the RPKI. This route object is the result of an automated
                RPKI-to-IRR conversion process performed by IRRd.
max-length:     24
origin:         AS16509
source:         RPKI  # Trust Anchor: ripe

route:          146.66.64.0/18
descr:          RPKI ROA for 146.66.64.0/18 / AS204508
remarks:        This AS204508 route object represents routing data retrieved
                from the RPKI. This route object is the result of an automated
                RPKI-to-IRR conversion process performed by IRRd.
max-length:     24
origin:         AS204508
source:         RPKI  # Trust Anchor: ripe


~$
~$ whois -h whois.radb.net 146.66.64.0/18
%  No entries found for the selected source(s).


~$

```

**Comment by lukastribus** [comment]
> If you do not agree, I would kindly ask for your rationale why it should be included in the output.

Here is the rationale:
https://blog.apnic.net/2018/08/01/treating-rpki-roas-as-irr-route6-objects/

**Comment by MrHamel** [comment]
I'll also full circle this with @job being bgpq4's project maintainer.

**Comment by m0yellow** [comment]
thanks for the detailed explanation. I check internally if we can drop the requirement for ripe db route objects for ripe IPs. For now I'll find a way to check that separately.
