### ISSUE TITLE
1.12 did not get marked as latest release

### ISSUE THREAD

**Issue by chenrui333** [bgp/bgpq4#107]
👋 looks like 1.12 did not get marked as latest release, raise this issue for some awareness! Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/162421

**Comment by job** [comment]
whoops, I forgot that tagging and releasing are not the same thing

fixed!

**Comment by chenrui333** [comment]
Thanks @job! (also nice id ;) )
