### ISSUE TITLE
Invalid WHOIS-Queries against irrd 4.4.2 from aarch64 Build

### ISSUE THREAD

**Issue by johannwagner** [bgp/bgpq4#108]
Hey,

we experienced some issues using bgpq4 on aarch64 in versions 1.11 and 1.12.
It seems like the WHOIS query from the aarch64 machine is not valid against irrd 4.4.2 and probably not valid at all.

We used the following query: `bgpq4 -h irrd.service.wobcom.de -4 AS-WOBCOM`

```shell
[nix-shell:~]$ bgpq4 -h irrd.service.wobcom.de -4 AS-WOBCOM
FATAL ERROR:EOF reading IRRd
```

I appended a `.pcap` file with two incoming WHOIS requests, the first one from the aarch64 machine, the second one with the x86_64 machine. 
Note: Renaming file to `.pcap` is required due to GH upload restrictions.

It seems like the whois query ends abruptly.
[irrd.txt](https://github.com/bgp/bgpq4/files/14560499/irrd.txt)

If you have any further questions, don't hesistate to contact us!

Best Regards, 
  Johann

**Comment by lukastribus** [comment]
You may want to provide more informations (OS informations, file bgpq4, ldd bgpq4, uname -a, cat /proc/cpuinfo), because it doesn't look like a general problem with aarch64 :

    root@debian-arm64-whoistest:~/bgpq4# file bgpq4
    bgpq4: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=3e7e967146b5fd92d341f18ec81387c15e336f6c, for GNU/Linux 3.7.0, with debug_info, not stripped
    root@debian-arm64-whoistest:~/bgpq4#
    root@debian-arm64-whoistest:~/bgpq4# ./bgpq4 -v
    bgpq4 - a versatile utility to generate BGP filters
    version: 1.12
    website: https://github.com/bgp/bgpq4
    maintainer: Job Snijders <job@sobornost.net>
    root@debian-arm64-whoistest:~/bgpq4#
    root@debian-arm64-whoistest:~/bgpq4# ./bgpq4 -h irrd.service.wobcom.de -4 AS-WOBCOM
    no ip prefix-list NN
    ip prefix-list NN permit 5.159.24.0/21
    ip prefix-list NN permit 5.183.20.0/22
    ip prefix-list NN permit 23.128.24.0/24
    ip prefix-list NN permit 23.129.64.0/24
    ip prefix-list NN permit 23.190.144.0/24
    ip prefix-list NN permit 27.50.0.0/22
    ip prefix-list NN permit 39.0.1.0/24
    ip prefix-list NN permit 44.31.0.0/22
    ip prefix-list NN permit 44.130.122.0/23
    ip prefix-list NN permit 45.10.24.0/24
    ip prefix-list NN permit 45.11.230.0/24
    ip prefix-list NN permit 45.12.203.0/24
    ip prefix-list NN permit 45.14.232.0/22
    ip prefix-list NN permit 45.66.88.0/24
    ip prefix-list NN permit 45.66.90.0/24
    ip prefix-list NN permit 45.86.153.0/24
    ip prefix-list NN permit 45.91.12.0/22
    ip prefix-list NN permit 45.92.48.0/22
    ip prefix-list NN permit 45.92.48.0/24
    ip prefix-list NN permit 45.92.49.0/24
    ip prefix-list NN permit 45.92.50.0/24
    ip prefix-list NN permit 45.92.51.0/24
    ip prefix-list NN permit 45.133.9.0/24
    ip prefix-list NN permit 45.137.56.0/22
    ip prefix-list NN permit 45.139.136.0/22
    ip prefix-list NN permit 45.140.183.0/24
    ip prefix-list NN permit 45.151.164.0/24
    ip prefix-list NN permit 45.151.166.0/24
    ip prefix-list NN permit 45.152.108.0/22
    ip prefix-list NN permit 45.152.108.0/24
    ip prefix-list NN permit 45.152.109.0/24
    ip prefix-list NN permit 45.152.110.0/24
    ip prefix-list NN permit 45.152.111.0/24
    ip prefix-list NN permit 45.152.228.0/22
    ip prefix-list NN permit 45.152.228.0/24
    ip prefix-list NN permit 45.152.229.0/24
    ip prefix-list NN permit 45.154.108.0/22
    ip prefix-list NN permit 45.154.108.0/23
    ip prefix-list NN permit 45.154.108.0/24
    ip prefix-list NN permit 45.154.109.0/24
    ip prefix-list NN permit 45.154.110.0/23
    ip prefix-list NN permit 45.154.110.0/24
    ip prefix-list NN permit 45.154.111.0/24
    ip prefix-list NN permit 45.155.77.0/24
    ip prefix-list NN permit 45.158.40.0/22
    ip prefix-list NN permit 45.158.40.0/24
    ip prefix-list NN permit 45.158.41.0/24
    ip prefix-list NN permit 45.158.42.0/23
    ip prefix-list NN permit 45.158.42.0/24
    ip prefix-list NN permit 45.158.43.0/24
    ip prefix-list NN permit 46.17.108.0/22
    ip prefix-list NN permit 62.176.224.0/19
    ip prefix-list NN permit 77.87.48.0/21
    ip prefix-list NN permit 77.87.48.0/24
    ip prefix-list NN permit 77.87.49.0/24
    ip prefix-list NN permit 77.87.50.0/23
    ip prefix-list NN permit 77.87.50.0/24
    ip prefix-list NN permit 77.87.51.0/24
    ip prefix-list NN permit 77.87.52.0/24
    ip prefix-list NN permit 77.87.53.0/24
    ip prefix-list NN permit 77.87.54.0/24
    ip prefix-list NN permit 77.87.55.0/24
    ip prefix-list NN permit 80.77.27.0/24
    ip prefix-list NN permit 84.205.64.0/24
    ip prefix-list NN permit 84.205.65.0/24
    ip prefix-list NN permit 84.205.66.0/24
    ip prefix-list NN permit 84.205.67.0/24
    ip prefix-list NN permit 84.205.68.0/24
    ip prefix-list NN permit 84.205.69.0/24
    ip prefix-list NN permit 84.205.70.0/24
    ip prefix-list NN permit 84.205.71.0/24
    ip prefix-list NN permit 84.205.72.0/24
    ip prefix-list NN permit 84.205.73.0/24
    ip prefix-list NN permit 84.205.74.0/24
    ip prefix-list NN permit 84.205.75.0/24
    ip prefix-list NN permit 84.205.76.0/24
    ip prefix-list NN permit 84.205.77.0/24
    ip prefix-list NN permit 84.205.78.0/24
    ip prefix-list NN permit 84.205.79.0/24
    ip prefix-list NN permit 84.205.80.0/24
    ip prefix-list NN permit 84.205.81.0/24
    ip prefix-list NN permit 84.205.82.0/24
    ip prefix-list NN permit 84.205.83.0/24
    ip prefix-list NN permit 84.205.84.0/24
    ip prefix-list NN permit 84.205.85.0/24
    ip prefix-list NN permit 84.205.86.0/24
    ip prefix-list NN permit 84.205.87.0/24
    ip prefix-list NN permit 84.205.88.0/24
    ip prefix-list NN permit 84.205.89.0/24
    ip prefix-list NN permit 84.205.90.0/24
    ip prefix-list NN permit 84.205.91.0/24
    ip prefix-list NN permit 84.205.92.0/24
    ip prefix-list NN permit 84.205.93.0/24
    ip prefix-list NN permit 84.205.94.0/24
    ip prefix-list NN permit 84.205.95.0/24
    ip prefix-list NN permit 87.253.188.0/24
    ip prefix-list NN permit 88.218.227.0/24
    ip prefix-list NN permit 91.186.32.0/19
    ip prefix-list NN permit 91.203.106.0/24
    ip prefix-list NN permit 91.210.224.0/24
    ip prefix-list NN permit 91.216.35.0/24
    ip prefix-list NN permit 91.240.92.0/24
    ip prefix-list NN permit 92.118.192.0/22
    ip prefix-list NN permit 93.94.4.0/23
    ip prefix-list NN permit 93.175.144.0/24
    ip prefix-list NN permit 93.175.146.0/24
    ip prefix-list NN permit 93.175.148.0/24
    ip prefix-list NN permit 93.175.149.0/24
    ip prefix-list NN permit 93.175.150.0/24
    ip prefix-list NN permit 93.175.151.0/24
    ip prefix-list NN permit 93.175.152.0/24
    ip prefix-list NN permit 93.175.153.0/24
    ip prefix-list NN permit 93.175.154.0/25
    ip prefix-list NN permit 93.175.154.128/28
    ip prefix-list NN permit 94.45.224.0/19
    ip prefix-list NN permit 103.1.0.0/22
    ip prefix-list NN permit 103.1.4.0/24
    ip prefix-list NN permit 103.232.206.0/23
    ip prefix-list NN permit 103.232.206.0/24
    ip prefix-list NN permit 103.232.207.0/24
    ip prefix-list NN permit 106.0.1.0/24
    ip prefix-list NN permit 128.121.4.32/29
    ip prefix-list NN permit 134.76.0.0/16
    ip prefix-list NN permit 134.76.175.0/24
    ip prefix-list NN permit 136.243.4.0/24
    ip prefix-list NN permit 136.243.28.0/24
    ip prefix-list NN permit 136.243.100.0/24
    ip prefix-list NN permit 136.243.221.0/24
    ip prefix-list NN permit 141.5.96.0/19
    ip prefix-list NN permit 141.39.220.0/22
    ip prefix-list NN permit 141.39.220.0/23
    ip prefix-list NN permit 141.39.220.0/24
    ip prefix-list NN permit 141.39.221.0/24
    ip prefix-list NN permit 141.39.222.0/23
    ip prefix-list NN permit 141.39.222.0/24
    ip prefix-list NN permit 141.39.223.0/24
    ip prefix-list NN permit 143.163.1.0/24
    ip prefix-list NN permit 143.163.12.0/22
    ip prefix-list NN permit 143.163.16.0/23
    ip prefix-list NN permit 143.163.21.16/28
    ip prefix-list NN permit 143.163.64.0/23
    ip prefix-list NN permit 143.163.66.0/23
    ip prefix-list NN permit 143.163.66.0/24
    ip prefix-list NN permit 143.163.67.0/24
    ip prefix-list NN permit 144.36.46.0/24
    ip prefix-list NN permit 144.36.52.0/24
    ip prefix-list NN permit 144.36.53.0/24
    ip prefix-list NN permit 144.36.54.0/23
    ip prefix-list NN permit 144.36.54.0/24
    ip prefix-list NN permit 144.36.90.0/23
    ip prefix-list NN permit 144.36.124.0/23
    ip prefix-list NN permit 144.36.136.0/23
    ip prefix-list NN permit 144.36.138.0/23
    ip prefix-list NN permit 144.36.152.0/23
    ip prefix-list NN permit 144.36.156.0/23
    ip prefix-list NN permit 144.36.160.0/23
    ip prefix-list NN permit 144.36.168.0/23
    ip prefix-list NN permit 144.36.170.0/23
    ip prefix-list NN permit 144.36.171.0/24
    ip prefix-list NN permit 144.36.172.0/24
    ip prefix-list NN permit 144.36.174.0/23
    ip prefix-list NN permit 144.36.180.0/24
    ip prefix-list NN permit 144.36.186.0/23
    ip prefix-list NN permit 144.36.186.0/24
    ip prefix-list NN permit 144.36.187.0/24
    ip prefix-list NN permit 144.36.212.0/23
    ip prefix-list NN permit 144.36.216.0/24
    ip prefix-list NN permit 144.36.252.0/23
    ip prefix-list NN permit 152.89.239.0/24
    ip prefix-list NN permit 159.167.188.0/22
    ip prefix-list NN permit 159.253.112.0/22
    ip prefix-list NN permit 159.253.116.0/23
    ip prefix-list NN permit 159.253.118.0/24
    ip prefix-list NN permit 159.253.119.0/24
    ip prefix-list NN permit 170.248.2.0/24
    ip prefix-list NN permit 170.248.11.0/24
    ip prefix-list NN permit 170.248.16.0/23
    ip prefix-list NN permit 170.248.24.0/21
    ip prefix-list NN permit 170.248.32.0/22
    ip prefix-list NN permit 170.248.39.0/24
    ip prefix-list NN permit 170.248.45.0/24
    ip prefix-list NN permit 170.248.56.0/21
    ip prefix-list NN permit 170.248.64.0/22
    ip prefix-list NN permit 170.248.68.0/22
    ip prefix-list NN permit 170.248.68.0/23
    ip prefix-list NN permit 170.248.72.0/22
    ip prefix-list NN permit 170.248.72.0/24
    ip prefix-list NN permit 170.248.80.0/23
    ip prefix-list NN permit 170.248.80.0/24
    ip prefix-list NN permit 170.248.83.0/24
    ip prefix-list NN permit 170.248.84.0/23
    ip prefix-list NN permit 170.248.85.0/24
    ip prefix-list NN permit 170.248.89.0/24
    ip prefix-list NN permit 170.248.102.0/23
    ip prefix-list NN permit 170.248.102.0/24
    ip prefix-list NN permit 170.248.103.0/24
    ip prefix-list NN permit 170.248.104.0/21
    ip prefix-list NN permit 170.248.112.0/21
    ip prefix-list NN permit 170.248.124.0/23
    ip prefix-list NN permit 170.248.133.0/24
    ip prefix-list NN permit 170.248.136.0/24
    ip prefix-list NN permit 170.248.141.0/24
    ip prefix-list NN permit 170.248.142.0/24
    ip prefix-list NN permit 170.248.163.0/24
    ip prefix-list NN permit 170.248.188.0/23
    ip prefix-list NN permit 170.248.213.0/24
    ip prefix-list NN permit 170.248.214.0/24
    ip prefix-list NN permit 170.248.219.0/24
    ip prefix-list NN permit 170.248.227.0/24
    ip prefix-list NN permit 170.251.16.0/22
    ip prefix-list NN permit 170.251.16.0/24
    ip prefix-list NN permit 170.251.17.0/24
    ip prefix-list NN permit 170.251.18.0/24
    ip prefix-list NN permit 170.251.19.0/24
    ip prefix-list NN permit 170.251.36.0/23
    ip prefix-list NN permit 170.251.48.0/23
    ip prefix-list NN permit 170.251.54.0/23
    ip prefix-list NN permit 170.251.56.0/22
    ip prefix-list NN permit 170.251.64.0/22
    ip prefix-list NN permit 170.251.84.0/23
    ip prefix-list NN permit 170.251.88.0/23
    ip prefix-list NN permit 170.251.90.0/23
    ip prefix-list NN permit 170.251.90.0/24
    ip prefix-list NN permit 170.251.91.0/24
    ip prefix-list NN permit 170.251.92.0/23
    ip prefix-list NN permit 170.251.94.0/24
    ip prefix-list NN permit 170.251.95.0/24
    ip prefix-list NN permit 170.251.97.0/24
    ip prefix-list NN permit 170.251.98.0/23
    ip prefix-list NN permit 170.251.98.0/24
    ip prefix-list NN permit 170.251.99.0/24
    ip prefix-list NN permit 170.251.104.0/23
    ip prefix-list NN permit 170.251.107.0/24
    ip prefix-list NN permit 170.251.116.0/24
    ip prefix-list NN permit 170.251.128.0/21
    ip prefix-list NN permit 170.251.128.0/22
    ip prefix-list NN permit 170.251.128.0/23
    ip prefix-list NN permit 170.251.128.0/24
    ip prefix-list NN permit 170.251.129.0/24
    ip prefix-list NN permit 170.251.130.0/23
    ip prefix-list NN permit 170.251.130.0/24
    ip prefix-list NN permit 170.251.131.0/24
    ip prefix-list NN permit 170.251.132.0/22
    ip prefix-list NN permit 170.251.132.0/23
    ip prefix-list NN permit 170.251.132.0/24
    ip prefix-list NN permit 170.251.132.0/30
    ip prefix-list NN permit 170.251.133.0/24
    ip prefix-list NN permit 170.251.134.0/23
    ip prefix-list NN permit 170.251.134.0/24
    ip prefix-list NN permit 170.251.135.0/24
    ip prefix-list NN permit 170.251.138.0/23
    ip prefix-list NN permit 170.251.138.0/24
    ip prefix-list NN permit 170.251.139.0/24
    ip prefix-list NN permit 170.251.145.0/24
    ip prefix-list NN permit 170.251.148.0/24
    ip prefix-list NN permit 170.251.161.0/24
    ip prefix-list NN permit 170.251.162.0/23
    ip prefix-list NN permit 170.251.180.0/23
    ip prefix-list NN permit 170.251.180.0/24
    ip prefix-list NN permit 170.251.181.0/24
    ip prefix-list NN permit 170.251.187.0/24
    ip prefix-list NN permit 170.251.192.0/23
    ip prefix-list NN permit 170.251.192.0/24
    ip prefix-list NN permit 170.251.193.0/24
    ip prefix-list NN permit 170.251.196.0/23
    ip prefix-list NN permit 170.251.196.0/24
    ip prefix-list NN permit 170.251.197.0/24
    ip prefix-list NN permit 170.251.200.0/23
    ip prefix-list NN permit 170.251.200.0/24
    ip prefix-list NN permit 170.251.201.0/24
    ip prefix-list NN permit 170.251.204.0/23
    ip prefix-list NN permit 170.251.204.0/24
    ip prefix-list NN permit 170.251.205.0/24
    ip prefix-list NN permit 170.251.208.0/23
    ip prefix-list NN permit 170.251.208.0/24
    ip prefix-list NN permit 170.251.209.0/24
    ip prefix-list NN permit 170.251.212.0/23
    ip prefix-list NN permit 170.251.212.0/24
    ip prefix-list NN permit 170.251.213.0/24
    ip prefix-list NN permit 170.251.220.0/23
    ip prefix-list NN permit 170.251.220.0/24
    ip prefix-list NN permit 170.251.221.0/24
    ip prefix-list NN permit 170.251.228.0/24
    ip prefix-list NN permit 170.251.229.0/24
    ip prefix-list NN permit 170.252.0.0/16
    ip prefix-list NN permit 170.252.16.0/23
    ip prefix-list NN permit 170.252.16.0/24
    ip prefix-list NN permit 170.252.17.0/24
    ip prefix-list NN permit 170.252.20.0/22
    ip prefix-list NN permit 170.252.32.0/24
    ip prefix-list NN permit 170.252.33.0/24
    ip prefix-list NN permit 170.252.34.0/24
    ip prefix-list NN permit 170.252.35.0/24
    ip prefix-list NN permit 170.252.36.0/24
    ip prefix-list NN permit 170.252.37.0/24
    ip prefix-list NN permit 170.252.38.0/24
    ip prefix-list NN permit 170.252.39.0/24
    ip prefix-list NN permit 170.252.43.0/24
    ip prefix-list NN permit 170.252.44.0/24
    ip prefix-list NN permit 170.252.45.0/24
    ip prefix-list NN permit 170.252.46.0/24
    ip prefix-list NN permit 170.252.47.0/24
    ip prefix-list NN permit 170.252.64.0/18
    ip prefix-list NN permit 170.252.80.0/21
    ip prefix-list NN permit 170.252.80.0/24
    ip prefix-list NN permit 170.252.109.0/24
    ip prefix-list NN permit 170.252.114.0/23
    ip prefix-list NN permit 170.252.122.0/24
    ip prefix-list NN permit 170.252.123.0/24
    ip prefix-list NN permit 170.252.126.0/24
    ip prefix-list NN permit 170.252.136.0/21
    ip prefix-list NN permit 170.252.136.0/22
    ip prefix-list NN permit 170.252.136.0/23
    ip prefix-list NN permit 170.252.136.0/24
    ip prefix-list NN permit 170.252.137.0/24
    ip prefix-list NN permit 170.252.138.0/23
    ip prefix-list NN permit 170.252.138.0/24
    ip prefix-list NN permit 170.252.139.0/24
    ip prefix-list NN permit 170.252.140.0/22
    ip prefix-list NN permit 170.252.140.0/23
    ip prefix-list NN permit 170.252.140.0/24
    ip prefix-list NN permit 170.252.141.0/24
    ip prefix-list NN permit 170.252.142.0/23
    ip prefix-list NN permit 170.252.142.0/24
    ip prefix-list NN permit 170.252.143.0/24
    ip prefix-list NN permit 170.252.144.0/23
    ip prefix-list NN permit 170.252.160.0/21
    ip prefix-list NN permit 170.252.168.0/23
    ip prefix-list NN permit 170.252.186.0/24
    ip prefix-list NN permit 170.252.187.0/24
    ip prefix-list NN permit 170.252.191.0/24
    ip prefix-list NN permit 170.252.208.0/24
    ip prefix-list NN permit 170.252.209.0/24
    ip prefix-list NN permit 170.252.215.0/24
    ip prefix-list NN permit 170.252.216.0/23
    ip prefix-list NN permit 170.252.216.0/24
    ip prefix-list NN permit 170.252.217.0/24
    ip prefix-list NN permit 170.252.253.0/24
    ip prefix-list NN permit 170.252.254.0/24
    ip prefix-list NN permit 178.255.16.0/22
    ip prefix-list NN permit 178.255.20.0/23
    ip prefix-list NN permit 178.255.22.0/24
    ip prefix-list NN permit 185.2.56.0/22
    ip prefix-list NN permit 185.65.241.0/24
    ip prefix-list NN permit 185.66.192.0/22
    ip prefix-list NN permit 185.66.193.0/24
    ip prefix-list NN permit 185.66.194.0/24
    ip prefix-list NN permit 185.66.195.0/24
    ip prefix-list NN permit 185.72.232.0/22
    ip prefix-list NN permit 185.106.84.0/22
    ip prefix-list NN permit 185.106.84.0/23
    ip prefix-list NN permit 185.106.86.0/23
    ip prefix-list NN permit 185.117.213.0/24
    ip prefix-list NN permit 185.161.80.0/22
    ip prefix-list NN permit 185.161.80.0/24
    ip prefix-list NN permit 185.161.81.0/24
    ip prefix-list NN permit 185.161.82.0/24
    ip prefix-list NN permit 185.161.83.0/24
    ip prefix-list NN permit 185.161.128.0/22
    ip prefix-list NN permit 185.177.204.0/22
    ip prefix-list NN permit 185.177.206.0/24
    ip prefix-list NN permit 185.177.207.0/24
    ip prefix-list NN permit 185.197.132.0/24
    ip prefix-list NN permit 185.206.208.0/22
    ip prefix-list NN permit 185.206.208.0/23
    ip prefix-list NN permit 185.206.208.0/24
    ip prefix-list NN permit 185.206.209.0/24
    ip prefix-list NN permit 185.206.210.0/23
    ip prefix-list NN permit 185.206.210.0/24
    ip prefix-list NN permit 185.206.211.0/24
    ip prefix-list NN permit 185.216.72.0/24
    ip prefix-list NN permit 185.220.101.0/24
    ip prefix-list NN permit 185.220.102.0/24
    ip prefix-list NN permit 185.220.200.0/22
    ip prefix-list NN permit 185.225.135.0/24
    ip prefix-list NN permit 185.225.140.0/22
    ip prefix-list NN permit 185.243.20.0/22
    ip prefix-list NN permit 185.245.96.0/24
    ip prefix-list NN permit 185.248.140.0/24
    ip prefix-list NN permit 192.31.196.0/24
    ip prefix-list NN permit 192.68.5.0/24
    ip prefix-list NN permit 192.68.6.0/24
    ip prefix-list NN permit 192.68.7.0/24
    ip prefix-list NN permit 192.68.11.0/24
    ip prefix-list NN permit 192.68.17.0/24
    ip prefix-list NN permit 192.70.141.0/24
    ip prefix-list NN permit 192.70.142.0/24
    ip prefix-list NN permit 192.70.150.0/24
    ip prefix-list NN permit 192.70.151.0/24
    ip prefix-list NN permit 192.70.152.0/24
    ip prefix-list NN permit 192.70.153.0/24
    ip prefix-list NN permit 192.70.154.0/24
    ip prefix-list NN permit 192.70.155.0/24
    ip prefix-list NN permit 192.70.156.0/24
    ip prefix-list NN permit 192.70.157.0/24
    ip prefix-list NN permit 192.70.158.0/24
    ip prefix-list NN permit 192.70.159.0/24
    ip prefix-list NN permit 192.108.74.0/24
    ip prefix-list NN permit 192.108.75.0/24
    ip prefix-list NN permit 192.108.76.0/22
    ip prefix-list NN permit 192.108.80.0/21
    ip prefix-list NN permit 192.108.89.0/24
    ip prefix-list NN permit 192.108.91.0/24
    ip prefix-list NN permit 192.108.92.0/24
    ip prefix-list NN permit 192.109.21.0/24
    ip prefix-list NN permit 192.109.42.0/24
    ip prefix-list NN permit 192.109.82.0/24
    ip prefix-list NN permit 192.129.15.0/24
    ip prefix-list NN permit 192.175.48.0/24
    ip prefix-list NN permit 192.251.226.0/24
    ip prefix-list NN permit 193.23.96.0/24
    ip prefix-list NN permit 193.23.244.0/24
    ip prefix-list NN permit 193.26.120.0/24
    ip prefix-list NN permit 193.29.188.0/24
    ip prefix-list NN permit 193.58.239.0/24
    ip prefix-list NN permit 193.96.24.0/24
    ip prefix-list NN permit 193.96.224.0/24
    ip prefix-list NN permit 193.104.168.0/24
    ip prefix-list NN permit 193.104.216.0/24
    ip prefix-list NN permit 193.109.132.0/23
    ip prefix-list NN permit 193.227.234.0/23
    ip prefix-list NN permit 194.31.198.0/24
    ip prefix-list NN permit 194.39.104.0/22
    ip prefix-list NN permit 194.45.135.0/24
    ip prefix-list NN permit 194.48.228.0/22
    ip prefix-list NN permit 194.48.228.0/23
    ip prefix-list NN permit 194.48.228.0/24
    ip prefix-list NN permit 194.48.229.0/24
    ip prefix-list NN permit 194.48.230.0/24
    ip prefix-list NN permit 194.48.231.0/24
    ip prefix-list NN permit 194.107.206.0/24
    ip prefix-list NN permit 194.107.207.0/24
    ip prefix-list NN permit 194.113.54.0/23
    ip prefix-list NN permit 194.113.54.0/24
    ip prefix-list NN permit 194.113.55.0/24
    ip prefix-list NN permit 194.114.32.0/23
    ip prefix-list NN permit 194.114.40.0/23
    ip prefix-list NN permit 194.114.44.0/22
    ip prefix-list NN permit 194.114.48.0/21
    ip prefix-list NN permit 194.114.56.0/22
    ip prefix-list NN permit 194.114.61.0/24
    ip prefix-list NN permit 194.114.62.0/23
    ip prefix-list NN permit 194.114.62.0/24
    ip prefix-list NN permit 194.114.63.0/24
    ip prefix-list NN permit 194.114.64.0/23
    ip prefix-list NN permit 194.114.66.0/23
    ip prefix-list NN permit 194.114.70.0/23
    ip prefix-list NN permit 194.114.74.0/24
    ip prefix-list NN permit 194.114.76.0/24
    ip prefix-list NN permit 194.114.77.0/24
    ip prefix-list NN permit 194.114.78.0/23
    ip prefix-list NN permit 194.114.80.0/23
    ip prefix-list NN permit 194.114.85.0/24
    ip prefix-list NN permit 194.114.94.0/23
    ip prefix-list NN permit 194.114.96.0/22
    ip prefix-list NN permit 194.114.96.0/23
    ip prefix-list NN permit 194.114.96.0/24
    ip prefix-list NN permit 194.114.97.0/24
    ip prefix-list NN permit 194.114.98.0/23
    ip prefix-list NN permit 194.114.100.0/22
    ip prefix-list NN permit 194.114.104.0/21
    ip prefix-list NN permit 194.114.104.0/24
    ip prefix-list NN permit 194.114.112.0/22
    ip prefix-list NN permit 194.114.116.0/22
    ip prefix-list NN permit 194.114.125.0/24
    ip prefix-list NN permit 194.114.126.0/24
    ip prefix-list NN permit 194.120.234.0/24
    ip prefix-list NN permit 194.150.168.0/23
    ip prefix-list NN permit 194.156.22.0/23
    ip prefix-list NN permit 194.156.22.0/24
    ip prefix-list NN permit 194.156.23.0/24
    ip prefix-list NN permit 195.12.38.0/24
    ip prefix-list NN permit 195.39.246.0/23
    ip prefix-list NN permit 195.39.246.0/24
    ip prefix-list NN permit 195.39.247.0/24
    ip prefix-list NN permit 195.54.164.0/23
    ip prefix-list NN permit 195.85.254.0/24
    ip prefix-list NN permit 195.88.60.0/23
    ip prefix-list NN permit 195.88.60.0/24
    ip prefix-list NN permit 195.88.61.0/24
    ip prefix-list NN permit 195.160.172.0/23
    ip prefix-list NN permit 195.160.172.0/24
    ip prefix-list NN permit 195.160.173.0/24
    ip prefix-list NN permit 195.191.196.0/23
    ip prefix-list NN permit 195.191.196.0/24
    ip prefix-list NN permit 195.191.197.0/24
    ip prefix-list NN permit 195.245.66.0/24
    ip prefix-list NN permit 195.245.114.0/23
    ip prefix-list NN permit 204.2.64.0/20
    ip prefix-list NN permit 213.162.128.0/19
    ip prefix-list NN permit 217.13.64.0/20
    ip prefix-list NN permit 217.197.80.0/20
    root@debian-arm64-whoistest:~/bgpq4#

**Comment by herrbett** [comment]
It seem this is a Darwin/MacOS specific problem.

Under MacOS with an ARM computer it looks like this to me:

```
bgpq4 -v
bgpq4 - a versatile utility to generate BGP filters
version: 1.11
website: https://github.com/bgp/bgpq4
maintainer: Job Snijders <job@sobornost.net>
```

```
 bgpq4 -h irrd.service.wobcom.de -4 AS-WOBCOM
FATAL ERROR:EOF reading IRRd
```

```
system_profiler SPSoftwareDataType SPHardwareDataType
Software:

    System Software Overview:

      System Version: macOS 14.4 (23E214)
      Kernel Version: Darwin 23.4.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Wobbook von herrbett
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 20 hours, 7 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,3
      Model Number: Z15G0007SD/A
      Chip: Apple M1 Pro
      Total Number of Cores: 8 (6 performance and 2 efficiency)
      Memory: 16 GB
      System Firmware Version: 10151.101.3
      OS Loader Version: 10151.101.3
```

**Comment by tangledhelix** [comment]
I get a different result on macOS (it works). There are some differences that may illuminate the problem. I am using a newer bgpq4, and an older macOS:

```
❯ bgpq4 -v
bgpq4 - a versatile utility to generate BGP filters
version: 1.12
website: https://github.com/bgp/bgpq4
maintainer: Job Snijders <job@sobornost.net>
```

```
❯ bgpq4 -h irrd.service.wobcom.de -4 AS-WOBCOM | wc -l
     475
```

```
❯ system_profiler SPSoftwareDataType SPHardwareDataType
Software:

    System Software Overview:

      System Version: macOS 14.2.1 (23C71)
      Kernel Version: Darwin 23.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: ******
      User Name: ******
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 10 days, 5 hours, 16 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: Mac14,5
      Model Number: Z17L001PDLL/A
      Chip: Apple M2 Max
      Total Number of Cores: 12 (8 performance and 4 efficiency)
      Memory: 64 GB
      System Firmware Version: 10151.61.4
      OS Loader Version: 10151.61.4
      Serial Number (system): ******
      Hardware UUID: ******
      Provisioning UDID: ******
      Activation Lock Status: Disabled
```

**Comment by dwcarder** [comment]
I was just about to open a new issue on this, but found this one is potentially the same symptom that I am seeing.

```
> bgpq4 AS-ESNET
FATAL ERROR:EOF reading IRRd

> bgpq4 -v
bgpq4 - a versatile utility to generate BGP filters
version: 1.12
website: https://github.com/bgp/bgpq4
maintainer: Job Snijders <job@sobornost.net>

> file /opt/homebrew/bin/bgpq4
/opt/homebrew/bin/bgpq4: Mach-O 64-bit executable arm64

> uname -a
Darwin dwc-laptop.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020 arm64

> system_profiler SPSoftwareDataType SPHardwareDataType
Software:

    System Software Overview:

      System Version: macOS 14.4.1 (23E224)
      Kernel Version: Darwin 23.4.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 11 days, 5 hours, 24 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: Mac14,9
      Model Number: Z17L001P8LL/A
      Chip: Apple M2 Pro
      Total Number of Cores: 12 (8 performance and 4 efficiency)
      Memory: 32 GB
      System Firmware Version: 10151.101.3
      OS Loader Version: 10151.101.3
      Activation Lock Status: Enabled

```
[bgpq4-ntt.pcap.gz](https://github.com/bgp/bgpq4/files/15171257/bgpq4-ntt.pcap.gz)

**Comment by job** [comment]
@dwcarder also on Mac?

**Comment by dwcarder** [comment]
yep on a very new mac laptop.
not exactly sure what I'm seeing in that pcap file, but it might be putting one byte in the packet at a time?

**Comment by job** [comment]
@dwcarder does `bgpq4 -h Whois.radb.net AS-ESNET` work?

**Comment by dwcarder** [comment]
Nope, from the same box, trying bgpq3 works fine.  ?!!
I also reinstalled bgpq4 from source (via homebrew) to make sure it wasn't using someone else's binary.

```
> time bgpq3 -h Whois.radb.net AS-ESNET | wc -l
     373

real	0m0.505s
user	0m0.007s
sys	0m0.011s

> time bgpq4 -h Whois.radb.net AS-ESNET
FATAL ERROR:EOF reading IRRd

real	0m31.275s
user	0m0.003s
sys	0m0.007s
```

**Comment by dwcarder** [comment]
```
> bgpq4 -d -h Whois.radb.net AS-ESNET
DEBUG: expander.c:1080 bgpq_expand Acquired sendbuf of 1 bytes

> bgpq3 -d -h Whois.radb.net AS-ESNET
DEBUG: bgpq_expander.c:797 bgpq_expand Acquired sendbuf of 1051008 bytes
```

well, that might match what I see on the wire...

**Comment by job** [comment]
Nice, we now have a reproducer in the CI environment that works on everything except Mac: https://github.com/bgp/bgpq4/actions/runs/8908593786/job/24464500498

**Comment by job** [comment]
I think this fixes it https://github.com/bgp/bgpq4/commit/f44bf47b1f05307134078a1d60faa9e2ceccf2c9

Can folks in this thread test the 'master' branch before I tag a new release?

**Comment by dwcarder** [comment]
I just built from the latest master with commit 0a83c7598d13e8d13d13f959ae5308536689317e and it's now working great on this platform.

**Comment by johannwagner** [comment]
Thanks for debugging and fixing this!

**Comment by job** [comment]
Fixed via https://github.com/bgp/bgpq4/releases/tag/1.13
