### ISSUE TITLE
Prefix aggregation not working as expected

### ISSUE THREAD

**Issue by LynxChaus** [bgp/bgpq4#118]
Attempt to grab MS address space and aggregate it - show strange result:
```
# bgpq4 -4 -A -F '%n/%l\n' AS8075 | grep ^209.185
209.185.240.0/23
209.185.240.0/24
```
209.185.240.0/24 should be skipped, since it fall into 209.185.240.0/23 - but it printed.

**Comment by job** [comment]
those two lines cannot be aggregated from a BGP routing perspective, `bgpq4` might not be the best tool for the job on its own.

Consider running the output through a tool like `aggregate` or `aggregate6` or [aggregate-prefixes](https://github.com/lamehost/aggregate-prefixes)

Example:
```
$ bgpq4 -4 -A -F '%n/%l\n' AS8075 | aggregate -q | grep ^209.185
209.185.240.0/23
```

**Comment by MrHamel** [comment]
Job,

What is the point of an aggregate feature if one must use a separate tool?

Ryan Hamel
________________________________

**Comment by job** [comment]
> Job, What is the point of an aggregate feature if one must use a separate tool? 

`bgpq4` does lossless aggregation for the purpose of configuring routers, for example using `ge` and `le` in Cisco land. What the OP is looking for is a different type of aggregation: suppress prefixes which are fully contained within another prefix. 

Lossless aggregation example:
```
10.0.0.0/24
10.0.1.0/24
+=
10.0.0.0/23 le 24 ge 24
```

lossly aggregation example:
```
10.0.0.0/24
10.0.1.0/24
+=
10.0.0.0/23
```

**Comment by MrHamel** [comment]
The aggregation result in both examples is the same, one just has additional parameters for the prefix-list/route-filter, instead of it being just a list.

Regardless, aggregation must suppress data, otherwise it's not aggregation.

Ryan Hamel

________________________________

**Comment by job** [comment]
They are not the same, one can be converted back into its original form of 2 x /24, the other has lost that information and remains a /23.

**Comment by MrHamel** [comment]
Can we meet in the middle where one can acknowledge the information being lost, and proceed forward without the need for another utility? There is a tier-1 carrier that would love this functionality and would reduce the amount of config lines dramatically. On a few AS-SETs, the difference is up to 50%

If this is used as part of prefix-list generator for ACLs or uRPF (yes, I know the pros and cons there), this compression can make all the difference in TCAM/line card resources.

Ryan Hamel
________________________________

**Comment by LynxChaus** [comment]
> those two lines cannot be aggregated from a BGP routing perspective

For my own purposes - seeing one /23 is better than /23 + /24. And I'm periodically use bgpq for generation ACL rules, where second /24 is USELESS and waste resources.

**Comment by job** [comment]
> > those two lines cannot be aggregated from a BGP routing perspective
> 
> For my own purposes - seeing one /23 is better than /23 + /24. And I'm periodically use bgpq for generation ACL rules, where second /24 is USELESS and waste resources.

Then piping it through another round of aggregation using one of the tools I mentioned is probably the fastest path forward.

**Comment by LynxChaus** [comment]
> Then piping it through another round of aggregation using one of the tools I mentioned is probably the fastest path forward.
I hate python and prefer one tool for generation, not combined|it|via|pipes|which|need|check|on|everystage, sorry -EPIPE

**Comment by job** [comment]
> Can we meet in the middle where one can acknowledge the information being lost, and proceed forward without the need for another utility? There is a tier-1 carrier that would love this functionality and would reduce the amount of config lines dramatically. On a few AS-SETs, the difference is up to 50% If this is used as part of prefix-list generator for ACLs or uRPF (yes, I know the pros and cons there), this compression can make all the difference in TCAM/line card resources. 

Sure, a new command line option letter would need to be picked for lossy aggregation, I wouldn’t want to change the existing behaviour of `-A`. Feel free to submit a pull request for review

**Comment by job** [comment]
To clarify for future readers: the `-A` functionality works as expected with the provided examples. The way `-A` works does not satisfy the requirements from OP. A new feature will need to be developed.

**Comment by MarianRychtecky** [comment]
Hi all, I do not expect BGPq4 to do the final aggregation of the returned set of prefixes. We do it using a Python config generator together with other sanitization, such as caching, etc. I agree that the aggregation has to be done somewhere, though.
