### ISSUE TITLE
Select timeout with large objects

### ISSUE THREAD

**Issue by DamianZaremba** [bgp/bgpq4#23]
Firstly, thank you for the efforts around bgpq4 and irrd, there are some significant improvements over the previous generations of tooling.

I'm not sure if this is best described here or is an item for irrd; when fetching large objects it appears that the execution throws a fatal error intermittently (often enough to be noticeable).

An example invocation;
```
$ bgpq4 -h rr.ntt.net -b -R24 -4 -l pxset AS1273:AS-CWW
FATAL ERROR:select timeout

$ bgpq4 -h rr.ntt.net -b -R24 -4 -l pxset -d AS1273:AS-CWW
DEBUG: bgpq_expander.c:893 bgpq_expand Acquired sendbuf of 1054144 bytes
DEBUG: bgpq_expander.c:915 bgpq_expand Sending '!!' to server to request for theconnection to remain open
DEBUG: bgpq_expander.c:924 bgpq_expand b->identify: Sending '!n bgpq4 0.0.6' to server.
DEBUG: bgpq_expander.c:935 bgpq_expand Got answer C
DEBUG: bgpq_expander.c:950 bgpq_expand Testing support for A queries
DEBUG: bgpq_expander.c:959 bgpq_expand Server supports A query
DEBUG: bgpq_expander.c:712 bgpq_expand_irrd expander: sending '!a4AS1273:AS-CWW
'
FATAL ERROR:select timeout
```

The timeout on IRRD's side appears to be 30 seconds by default, with bgpq4 using a 10 second select timeout (no options to specify `!T`).

Locally patching the timeout definition to `struct timeval timeout = {30, 0};` appears to enable bgpq4 to work reliably, however this may well not be ideal for other performance reasons.

**Comment by DamianZaremba** [comment]
After running the below patch in my CI system for the ~2 months there's been no timeout occurrence, using the 0.0.6 release directly (locally or within the same CI system) returns timeouts intermittently.

Based on this I believe my original 'guess' as to the source of this issue (above) to be correct, the below is not entirely suitable as a general fix, however I can probably look at exposing this via a `timeout` option if this is something the community is interesting in/willing to accept.
```
diff -r bgpq4-0.0.6.orig/bgpq_expander.c bgpq4-0.0.6/bgpq_expander.c
480c480
< 	struct timeval timeout = {10, 0};
---
> 	struct timeval timeout = {30, 0};
```

**Comment by job** [comment]
if you want to submit a pull request that bumps the timer from 10 to 30 seconds I am OK with that! Thank your debugging this issue

If I may ask, where on the planet are you running bgpq4? The `rr.ntt.net` instance is in Dallas, US - and I wonder if you are running into this because of latency of your connection to the instance.

**Comment by robert-scheck** [comment]
From AS3209 in Germany; my latency to rr.ntt.net is about 160-165 ms:

```
$ time bgpq4 -h rr.ntt.net -b -R24 -4 -l pxset AS1273:AS-CWW > /dev/null

real	0m16,575s
user	0m5,301s
sys	0m0,352s
$ 
```

It takes ~ 9 seconds of the struct timeval timeout, based on a custom-compiled version.

**Comment by DamianZaremba** [comment]
The regular failures I was seeing where from nodes in gcp's us-central-1 region, which is ~26ms away.

I can replicate this (intermittently) from my local machine in the Netherlands which is around 165-170ms behind Ziggo.

I'll cut a PR to bump this up now, apologies for not getting back to this sooner.

**Comment by DamianZaremba** [comment]
Submitted as https://github.com/bgp/bgpq4/pull/27

**Comment by job** [comment]
cool! Thanks, I think we can close this out now, can we?
