### ISSUE TITLE
force exclude/filter certain ASN "members" from AS-SET

### ISSUE THREAD

**Issue by nvieirapt** [bgp/bgpq4#30]
Hello,

I've seen certain AS-SET lists with false members assigned on a given set.

This will create a certain undesirable prefix-list and cause potential problems  (we really need AS Cones).

In the meantime implementing a flag where one can list a certain well known AS to be filtered uppon creation would help.

can this be implemented ?

cheers

**Comment by job** [comment]
You can use the `EXCEPT` keyword to instruct bgpq4 to ignore one or more objects.

Example:

```
$ bgpq4 AS15562:AS-SNIJDERS EXCEPT AS15526 AS43997 AS-KING | wc -l
     105

$ bgpq4 AS15562:AS-SNIJDERS | wc -l
     136
```
