### ISSUE TITLE
Suggestion to Packaging Effort - Add a "bgp3 alias to bgpq4" package

### ISSUE THREAD

**Issue by fischerdouglas** [bgp/bgpq4#31]
bgpq4 is almost fully compatible with bgpq3 features.
Now, by heart, I can just remember the asdot notation that was removed from  bgpq4.

There are several tools that use bgp3 as an IRR querier.
Some of them hardcoded.

Creating a simple package that would add an alias from "bgpq3" to "bgpq4" could help the adoption of  bgpq4.

**Comment by robert-scheck** [comment]
If this happens on upstream side, make it optional, please. Fedora and EPEL have bgpq3 and bgpq4 packages which are both actively maintained.

**Comment by job** [comment]
I will not implement this. Operators have to decide for themselves which package they want to use.

There are many many differences between bgpq3 and bgpq4.
