### ISSUE TITLE
Refine not working as expected with Mikrotik Output

### ISSUE THREAD

**Issue by RaidAndFade** [bgp/bgpq4#32]
Try the following: 
`bgpq4 -6 AS13335 -R 48`
As expected, it produces similar output as below:
```
# bgpq4 -6 AS13335 -R 48  
no ipv6 prefix-list NN
ipv6 prefix-list NN permit 2400:cb00::/32 le 48
...
```
Meaning anything from the /32 down to a /48 is accepted.

Now try that same command with `-K`
It results in the following style of output:
```
# bgpq4 -6 AS13335 -R 48 -K
/routing filter add action=accept chain="NN-V6" prefix=2400:cb00::/32 prefix-length=48
```
This output does not accurately reproduce the same functionality as before, this filter will only allow /48  to be accepted, not le 48 ge 32 as the above did.

I believe the issue arises from the following code snippet, which does not properly account for this use-case:
https://github.com/bgp/bgpq4/blob/62b2a56af76895b33c29265ba41bf107e3e44966/bgpq4_printer.c#L1804-L1808

**Comment by RaidAndFade** [comment]
I believe the appropriate resolution would be to replicate similar functionality as to `bgpq4_print_format_prefix`, which accurately produces the desired output.

**Comment by job** [comment]
@RaidAndFade thank you for the report. Is it feasible for you to put together a pull-request?

**Comment by RaidAndFade** [comment]
@job I could attempt to but my C skills are quite rusty

**Comment by job** [comment]
@RaidAndFade no worries, mineis bad too, i am happy to review your work!

**Comment by RaidAndFade** [comment]
@job Heh, Sure. I'll give it a shot when I have some free time. 

In the meantime I'm working around this issue in my own setup using the aforementioned `-F` flag with a similar format string as the desired output. 

The workaround, for those interested is:
 `-F '/routing filter add action=accept chain="%N-v6" prefix=%n/%l prefix-length=%a-%A'`
