### ISSUE TITLE
Implementation of 6WIND prefix/access lists ?

### ISSUE THREAD

**Issue by jczmok-iag** [bgp/bgpq4#38]
Hi, can somebody implement support for 6wind Routers ?

the config snippets look like this: 

/ routing ipv4-prefix-list as12345-prefixes
/ routing ipv4-prefix-list as12345-prefixes seq 10 address 1.1.1.1/23 policy permit

thanks!

**Comment by job** [comment]
@jczmok-iag you can either specify a FMT with the `-F` option (see man page), or you'll have to find someone to write a bit of C and submit a pull request
