### ISSUE TITLE
IOS XR example ?

### ISSUE THREAD

**Issue by omelendres** [bgp/bgpq4#39]
Searching for the correct syntax to make it work for XR. Thanks !

```
$ bgpq4  -Xl test AS1234
FATAL ERROR:Sorry, only prefix-sets and as-paths supported for IOS XR
```

**Comment by lukastribus** [comment]
I don't think it should be more complicated than that.

Looks like something broke with the 7d6c4421d change:

```
$ git checkout 7d6c4421de9f4b6b585da0350ac25d9a412af088
$ make clean; ./bootstrap; ./configure && make && ./bgpq4 -X AS1234
[...]
FATAL ERROR:Sorry, only prefix-sets and as-paths supported for IOS XR
$
$ git checkout e3974c5469047348b0c3189d3fe8d38262ff2614
[...]
$ make clean; ./bootstrap; ./configure && make && ./bgpq4 -X AS1234
no prefix-set NN
prefix-set NN
 1.1.2.0/24,
 193.110.32.0/21,
 194.110.40.0/23
end-set
$

```

**Comment by omelendres** [comment]
You are right, replicated the solution provided.

**Comment by job** [comment]
thank you for reporting this

@omelendres please don't use the `git checkout xxx` 'solution', as pinning to an holder version of `bgpq4` is not a good solution. I hope this is now fixed in `master`. Let me know if you find any other issues.

**Comment by omelendres** [comment]
thank you @job and @lukastribus. The master works now after your last commit!
