### ISSUE TITLE
Not Expanding Range from IRR

### ISSUE THREAD

**Issue by mhlambert** [bgp/bgpq4#51]
We have a route-set defined in IRR with relevant lines

```
route-set:  AS5050:RS-BVIU
members:    206.127.136.0/21^21-26, 209.114.140.0/23^23-24
```
If I run this through bgpq3, I get what I would expect:

```
% bgpq3 -4 -A -l foo as5050:rs-bviu
no ip prefix-list foo
ip prefix-list foo permit 206.127.136.0/21 le 26
ip prefix-list foo permit 209.114.140.0/23 le 24
```
(peval from irrtoolset will also expand the more-specific prefixes.)

But if I use bgpq4, it apparently doesn't even recognize the prefixes:
```
% bgpq4 -4 -A -l foo as5050:rs-bviu
no ip prefix-list foo
! generated prefix-list foo is empty
ip prefix-list foo deny 0.0.0.0/0
```
This is version 1.4 from Homebrew on macOS:

```
% bgpq4 -v
bgpq4 - a versatile utility to generate BGP filters
version: 1.4
website: https://github.com/bgp/bgpq4
maintainer: Job Snijders <job@sobornost.net>
```

**Comment by job** [comment]
Hi! Thanks for the report.

I think the issue is with the `rr.ntt.net` server (which is the default of `bgpq4`, in contrast to `bgpq3` which defaults to `whois.radb.net`).

It was recently discovered there is an issue with `route-set` expansion in IRRd v4: https://github.com/irrdnet/irrd/issues/543
