### ISSUE TITLE
Profiling basics

### ISSUE THREAD

**Issue by ghenry** [bgp/bgpq4#54]
Hi all,

Just having some profiling fun. If anyone is interested (1793 lines via `wc -l` for output prefixes for NTT ASN):

```
./bootstrap
CFLAGS="-pg -g" ./configure
make
./bgpq4 -A AS2914
gprof bgpq4 gmon.out > gprof_output.txt
gprof bgpq4 | gprof2dot | dot -Tpng -o output.png
```
Files attached. I'm working through to have a play. I hope no one minds?

![output](https://user-images.githubusercontent.com/159608/135866104-eea75822-b0c3-4b0c-888c-44130d0f028e.png)
[gprof_output.txt](https://github.com/bgp/bgpq4/files/7278621/gprof_output.txt)

Is the NTT ASN the biggest out there?

Thanks,
Gavin.

**Comment by job** [comment]
Thanks for sharing!
