### ISSUE TITLE
Junos: AS-Path filtering without regex 

### ISSUE THREAD

**Issue by unfokus** [bgp/bgpq4#56]
JunOS 21.3R1 added a feature to allow AS-Path filtering without the use of regexes. According to Juniper this is supposed to be less resource heavy as the classic regex-style filters. Also, diffs between policy updates are way shorter and more readable.
https://www.juniper.net/documentation/us/en/software/junos/routing-policy/topics/topic-map/Improve-as-path-lookup.html

Quote of the [JunOS 21.3R1 release notes](https://www.juniper.net/documentation/us/en/software/junos/release-notes/21.3/junos-release-notes-21.3r1/junos-release-notes-21.3r1.pdf)

> Junos OS Release 21.3R1, you can configure BGP policies to check for an autonomous system (AS) match in an AS path without using regular expressions. The BGP policy compares the AS to an AS-list or AS-list-group and returns true if it finds a match. You can configure the BGP policy to check for a matching origin, neighbor, or transit AS. This feature provides a faster alternative to match origin, transit, and peer AS numbers than using a regular expression.
> Configure this feature using the as-path-neighbors, as-path-origins, or as-path-transits option at the [edit policy-options policy-statement policy-name from] hierarchy level. For each type of match, use (as-list | 144 as-list-group) as-list-name/as-list-group-name to specify the list or group of AS paths to compare the match to. Configure the AS list or AS group at the [edit policy-options] hierarchy level.

**Configuration Example:**
Traditional:
```
policy-options {
 as-path-group AS9136 {
    as-path a0 "^9136(9136)*$";
    as-path a1 "^9136(.)*(112|248|250|3573|3624|6766|12654|12748)$";
    as-path a2 "^9136(.)*(13020|13130|20488|21158|24956|29670|31451|34219)$";
    as-path a3 "^9136(.)*(39225|39788|44194|48387|48777|49009|49745|49933)$";
    as-path a4 "^9136(.)*(50017|50472|59645|60729|64404|64475|132362|200490)$";
    as-path a5 "^9136(.)*(201173|201701|202329|204675|204911|205597|206236|206313)$";
    as-path a6 "^9136(.)*(206356|206554|206618|206740|206813|206946|207180|207871)$";
    as-path a7 "^9136(.)*(208135|208294|208395|208633|208727|208772|208893|208942)$";
    as-path a8 "^9136(.)*(209347|209530|209894|210916|211479|212520|212989|213027)$";
    as-path a9 "^9136(.)*(213106|213341|396507)$";
  }
}
```

With the new feature:
```
policy-options {
  as-list AS9136_ORIGIN members [ 112 248 250 3573 3624 6766 9136 12654 12748 13020 13130 20488 21158 24956 29670 31451 34219 39225 39788 44194 48387 48777 49009 49745 49933 50017 50472 59645 60729 64404 64475 132362 200490 201173 201701 202329 204675 204911 205597 206236 206313 206356 206554 206618 206740 206813 206946 207180 207871 208135 208294 208395 208633 208727 208772 208893 208942 209347 209530 209894 210916 211479 212520 212989 213027 213106 213341 396507 ];
  as-list AS9136_NEIGHBOR members 9136;

  policy-statement AS9136_FILTER {
    term AS_PATH_MATCH {
      from {
        as-path-neighbors as-list AS9136_NEIGHBOR;
        as-path-origins as-list AS9136_ORIGIN;
      }
      then next policy;
    }
    then reject;
  }
}
```

**Explanation:**
The new options can only be used in a policy-statement. So we need to decide whether bgpq4 should generate only the as-list(-group)s or both, the lists and a policy.
In this example I have chosen to use plain as-lists, as-list-groups would work as well.
`as-path-neighbors` checks the first ASN in the path against the as-list.
`as-path-origins` checks the last ASN in the path against the as-list.
There is `as-path-transits` as well, which can be used to filter the ASNs allowed in between the first and last ASN.
It does not seem like it's possible to have a negative match on these, so we have to check them together or in separate policies. (or is there a secret way to invert the condition on JunOS?)

Caution:
- We need to add our Peer AS to the as-path-origins list.
- On a RS session we would not want to enforce the `as-path-neighbor`, or better, check against a list of the ASNs directly connected to the IXP. But there's no way to extract this from IRRDB, as IXPs add the AS-Sets, and not the ASNs, of the member to their AS-SET.
- If we want to use the as-path-transit feature, we need to check if we need to add our peer and origin ASNs to the list as well, for the case that there are path prepends. The documentation is not clear about whether it ignores prepended ASNs at the beginning or end of the as path. (I can check this in the lab)

**Comment by job** [comment]
A configuration example would be appreciated

**Comment by unfokus** [comment]
@job I have added an example and an explanation to the original post.

**Comment by unfokus** [comment]
thanks for merging! :)
