### ISSUE TITLE
Use pledge on OpenBSD

### ISSUE THREAD

**Issue by job** [bgp/bgpq4#6]
If compiled on OpenBSD, make use of `pledge()` system call to restrict attack surface.

**Comment by MrHamel** [comment]
Maybe you can rename this issue to "Best Security Practices for *nix Platforms", since Capsicum exists for FreeBSD, and Linux may have some tie ins for SELinux and AppArmor.

**Comment by job** [comment]
@MrHamel those would be separate issues / pull requests... if anyone steps up to volunteer!
