### ISSUE TITLE
enormous number of prefixes in filter

### ISSUE THREAD

**Issue by MarkRudenko** [bgp/bgpq4#63]
Hello team,
We faced a problem when we generate a prefix filter there is an enormous number of prefixes there.
These prefixes are not related to AS-SET according to which we build a filter.

For example:

% bgpq4 AS44395:AS-ALL | wc -l
 1333435

% bgpq4 AS-FIBERNET | wc -l
 1333435

We checked these AS-SETs and their members don't have such a big number of prefixes. It looks like a whole full view inside the prefix list.

Maybe problem is that both AS-SETs have each other as a member.

**Comment by lukastribus** [comment]
Not sure whats up, but irrexplorer also chokes on this:

https://irrexplorer.nlnog.net/as-set/AS-FIBERNET

**Comment by job** [comment]
I guess this no longer is an issue

```
$ bgpq4 AS-FIBERNET | wc -l
     182
$ bgpq4 AS44395:AS-ALL | wc -l
     212
```
