### ISSUE TITLE
Support -3 as a no-op for bgpq3 compatibility

### ISSUE THREAD

**Issue by rlaager** [bgp/bgpq4#89]
It would be nice if bgpq4 could take -3 as a no-op for bgpq3 compatibility. This would allow bgpq4 to be used as a drop-in replacement with IXP Manager:
https://github.com/inex/IXP-Manager/issues/844

**Comment by job** [comment]
Sure! Seems like it would help some folks. Do you want to make a pull request?

**Comment by rlaager** [comment]
Yeah, I can whip something up in the next couple days.

**Comment by job** [comment]
Thanks!
